### PR TITLE
Add back _EXECUTOR_PLUGIN_DEFAULTS to ssh executor

### PR DESCRIPTION
**Pull request by AlejandroEsquivel**
- [ ] I have added the tests to cover my changes.
- [x] I have updated the documentation, VERSION, and CHANGELOG accordingly.
- [x] I have read the CONTRIBUTING document.

### CODE REVIEW

**Comment by AlejandroEsquivel** [comment]
@cjao @kessler-frost I have added the `_EXECUTOR_PLUGIN_DEFAULTS` var to the ssh executor so that default values for the executor are written to the config file, let me know however if this is not needed

**Review by cjao — APPROVED** [review]

**Comment by cjao** [comment]
Thanks @AlejandroEsquivel. I'm surprised that the SSH executor still worked without `_EXECUTOR_PLUGIN_DEFAULTS`.

**Comment by kessler-frost** [comment]
@AlejandroEsquivel I agree, we should add it back, I have to admit that it was me who removed it in the earlier PR because I couldn't see its impact, plus we were defining the same parameters twice. @cjao technically all of the plugins should work without `_EXECUTOR_PLUGIN_DEFAULTS`, its presence just makes covalent write to the config file (which again after today's discussion, might not be the best idea).

I think it will also be better, even if we do want to write to the config, if the defaults were determined directly from the default values in the constructor, instead of having a separate variable.

**Comment by cjao** [comment]
>I think it will also be better, even if we do want to write to the config, if the defaults were determined directly from the default values in the constructor, instead of having a separate variable.

+1 for this

**Pull request merged**
